version: 2

project_name: porkbun-dyndns

release:
  github:
    owner: thrau
    name: porkbun-dyndns

  draft: true

before:
  hooks:
    - go mod tidy

builds:
  - id: porkbun-dns
    main: ./cmd/porkbun-dns
    binary: porkbun-dns
    env:
      - CGO_ENABLED=0
    goos: [linux, darwin]
    goarch: [386, amd64, arm64]

  - id: porkbun-ddnsd
    main: ./cmd/porkbun-ddnsd
    binary: porkbun-ddnsd
    env:
      - CGO_ENABLED=0
    goos: [linux, darwin]
    goarch: [386, amd64, arm64]

archives:
  - id: bundle
    ids:
      - porkbun-dns
      - porkbun-ddnsd
    formats: [zip]
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}

nfpms:
  - id: porkbun-dyndns-deb
    package_name: porkbun-dyndns
    ids:
      - porkbun-dns
      - porkbun-ddnsd
    formats: [deb, archlinux]
    vendor: thrau
    homepage: https://github.com/thrau/porkbun-dyndns
    maintainer: thrau
    description: Porkbun Dynamic DNS daemon and CLI tools
    license: MIT
    contents:
      - src: packaging/nfpms/systemd/porkbun-ddnsd.service
        dst: /etc/systemd/system/porkbun-ddnsd.service
      - src: packaging/nfpms/config.toml
        dst: /etc/porkbun-ddnsd/config.toml
        type: config|noreplace
    scripts:
      postinstall: packaging/nfpms/postinstall.sh
    deb:
      lintian_overrides:
        - statically-linked-binary
    archlinux:
      packager: thrau

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
